# Generated by Django 3.1.7 on 2021-03-14 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faculty',
            options={'verbose_name_plural': 'faculties'},
        ),
    ]
